# Generated by Django 5.1.6 on 2025-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('desk', 'Desk'), ('user', 'User'), ('lab_technician', 'Lab Technician'), ('cashier', 'Cashier')], default='user', max_length=20),
        ),
    ]
