# Generated by Django 5.1.6 on 2025-03-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('Prescription', 'Prescription'), ('LabRequest', 'Lab Request')], max_length=20)),
                ('data', models.TextField()),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
