# Generated by Django 5.1.6 on 2025-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='blockchain_record_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
