# Generated by Django 5.1.6 on 2025-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_report', '0004_labreport_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='blockchain_record_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
