# Generated by Django 5.1.6 on 2025-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.PositiveIntegerField()),
                ('transaction_hash', models.CharField(max_length=66)),
                ('data_hash', models.CharField(max_length=64)),
                ('record_type', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
                ('doctor_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
