# Generated by Django 5.1.6 on 2025-03-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('doctors', '0004_doctor_temp_slot_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptommapping',
            name='specialization',
        ),
        migrations.AddField(
            model_name='symptommapping',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
