# Generated by Django 5.1.6 on 2025-03-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_remove_symptommapping_specialization_and_more'),
        ('doctors', '0004_doctor_temp_slot_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptommapping',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
