# Generated by Django 5.1.6 on 2025-03-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Treated', 'Treated'), ('Skipped', 'Skipped')], default='Pending', max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('last_email_sent', models.DateTimeField(blank=True, help_text='Timestamp of the last wait time email sent', null=True)),
                ('can_update', models.BooleanField(default=False, help_text='True if the appointment can be updated (past due by 2 hours)')),
            ],
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('patient_timer', models.PositiveIntegerField(default=1200, help_text='Remaining time in seconds for the current patient')),
            ],
        ),
    ]
