# Generated by Django 5.1.6 on 2025-02-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_blood_group_appointment_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
    ]
