# Generated by Django 5.1.6 on 2025-02-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='extra_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Treated', 'Treated'), ('Skipped', 'Skipped')], default='Pending', max_length=20),
        ),
    ]
