# Generated by Django 5.1.6 on 2025-03-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_sessionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='can_update',
            field=models.BooleanField(default=False, help_text='True if the appointment can be updated (past due by 2 hours)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='extra_time',
            field=models.PositiveIntegerField(default=0, help_text='Additional minutes added to treatment time, stored in DB'),
        ),
    ]
