# Generated by Django 5.1.6 on 2025-03-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_can_update_alter_appointment_extra_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='extra_time',
        ),
    ]
