# Generated by Django 5.1.6 on 2025-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_remove_appointment_extra_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last wait time email sent', null=True),
        ),
    ]
