# Generated by Django 5.1.6 on 2025-03-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_last_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionhistory',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_session', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='patient_timer',
            field=models.PositiveIntegerField(default=1200, help_text='Remaining time in seconds for the current patient'),
        ),
    ]
