# Generated by Django 5.1.6 on 2025-03-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='doctors/')),
                ('available_slots', models.TextField(help_text='Comma-separated available slots (e.g., 09:00,15:00,19:00)')),
                ('temp_slot_adjustment', models.IntegerField(default=0, help_text='Temporary hours added to slots (e.g., 1 or 2 hours)')),
            ],
        ),
    ]
