# Generated by Django 5.1.6 on 2025-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_slots',
            field=models.TextField(default='', help_text='Comma-separated available slots (e.g., 9AM-12PM,3PM-5PM)'),
        ),
    ]
