# Generated by Django 5.1.6 on 2025-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_slots',
            field=models.TextField(help_text='Comma-separated available slots (e.g., 09:00,15:00,19:00)'),
        ),
    ]
