# Generated by Django 5.1.6 on 2025-02-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='temp_slot_adjustment',
            field=models.IntegerField(default=0, help_text='Temporary hours added to slots (e.g., 1 or 2 hours)'),
        ),
    ]
